<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateCustomersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('customers', function (Blueprint $table) {
            $table->id();

            // Table to be sorted for nullable fields and defaults

            $table->boolean('ACATOtherCare');
            $table->boolean('ACHForm_c');
            $table->boolean('AGUseGoodDefaultMark');
            $table->boolean('AddlHdlgFlag');
            $table->boolean('AddressVal');
            $table->boolean('AdvancedLaborRate');
            $table->boolean('AgingCreditHold');
            $table->boolean('AllowAltBillTo');
            $table->boolean('AllowAsAltRemitTo');
            $table->boolean('AllowOTS');
            $table->boolean('AllowShipTo3');
            $table->boolean('ApplyChrg');
            $table->boolean('ApplyHoldToOrders');
            $table->boolean('B2BWebCust_c');
            $table->boolean('COD');
            $table->boolean('CODCheck');
            $table->boolean('CODFreight');
            $table->boolean('COIsOneTimeCust');
            $table->boolean('CheckConfirmCapPromise');
            $table->boolean('CheckDateCapPromise');
            $table->boolean('CheckDuplicatePO');
            $table->boolean('CheckUpdateCapPromise');
            $table->boolean('Collections');
            $table->boolean('ConsolidateLinesPerPart');
            $table->boolean('ConsolidateSO');
            $table->boolean('CreditCardOrder');
            $table->boolean('CreditHold');
            $table->boolean('CreditIncludeOrders');
            $table->boolean('CreditIncludePI');
            $table->boolean('DeclaredIns');
            $table->boolean('DeferredRev');
            $table->boolean('DemandCheckCUMM');
            $table->boolean('DemandCheckConfig');
            $table->boolean('DemandCheckForPart');
            $table->boolean('DemandCheckForRev');
            $table->boolean('DemandCloseNoMatch');
            $table->boolean('DemandCloseRejSkd');
            $table->boolean('DemandSplitSched');
            $table->boolean('DemandUnitPriceDiff');
            $table->boolean('DirectDebiting');
            $table->boolean('DmdCheckPartialShip');
            $table->boolean('DocOnly');
            $table->boolean('EInvoice');
            $table->boolean('ERSOrder');
            $table->boolean('ETCAddrChg');
            $table->boolean('EnableGlobalCust');
            $table->boolean('ExcFromVal');
            $table->boolean('ExternalCRMSyncRequired');
            $table->boolean('ExternalDeliveryNote');
            $table->boolean('FinCharges');
            $table->boolean('GlbNACreditIsShare');
            $table->boolean('GlbNAParentCreditIsUsed');
            $table->boolean('GlobalCredIncOrd');
            $table->boolean('GlobalCredIncPI');
            $table->boolean('GlobalCust');
            $table->boolean('GlobalLock');
            $table->boolean('HasBank');
            $table->boolean('Hazmat');
            $table->boolean('ICCust');
            $table->boolean('ICTrader');
            $table->boolean('ImporterOfRecord');
            $table->boolean('IntRunChangeCountry');
            $table->boolean('IntegrationFlag');
            $table->boolean('InvPerPackLine');
            $table->boolean('InvcOrderCmpDflt');
            $table->boolean('LLLBAssetAssess');
            $table->boolean('LOQBookCaFinishing');
            $table->boolean('LOQVariations');
            $table->boolean('MXGeneralPublic');
            $table->boolean('NACreditCust');
            $table->boolean('NACreditUpdated');
            $table->boolean('NoContact');
            $table->boolean('NonStdPkg');
            $table->boolean('NotifyFlag');
            $table->boolean('OTSmartString');
            $table->boolean('OneInvPerPS');
            $table->boolean('OrderHoldForReview');
            $table->boolean('PECollectionAgent');
            $table->boolean('PEGoodsContributor');
            $table->boolean('PENoAddress');
            $table->boolean('PENotFound');
            $table->boolean('PEWithholdAgent');
            $table->boolean('PeriodicBilling');
            $table->boolean('PrintAck');
            $table->boolean('PrintLabels');
            $table->boolean('PrintStatements');
            $table->boolean('ResDelivery');
            $table->boolean('RfqAttachAllow');
            $table->boolean('SatDelivery');
            $table->boolean('SatPickup');
            $table->boolean('SendToFSA');
            $table->boolean('ServAlert');
            $table->boolean('ServHomeDel');
            $table->boolean('ServRelease');
            $table->boolean('ServSignature');
            $table->boolean('SyncToExternalCRM');
            $table->boolean('TerritoryLock');
            $table->boolean('ThirdPLCust');
            $table->boolean('UPSQuantumView');
            $table->boolean('UseBlindShipping');
            $table->boolean('Variations');
            $table->boolean('WIShippingCosts');
            $table->boolean('WebCustomer');
            $table->dateTime('ChangeDate');
            $table->dateTime('CreditClearDate');
            $table->dateTime('CreditReviewDate');
            $table->dateTime('EstDate');
            $table->float('AnnualRevenue', 5, 2);
            $table->float('CODAmount', 5, 2);
            $table->float('ChrgAmount', 5, 2);
            $table->float('DeclaredAmt', 5, 2);
            $table->float('DiscountPercent', 5, 2);
            $table->float('GlbNACreditSharedPrc', 5, 2);
            $table->float('GlbNAParentCreditPrc', 5, 2);
            $table->float('LLLBLifeTimeCap', 5, 2);
            $table->float('LLLBMeansTestAmt', 5, 2);
            $table->float('LLLBMeansTestFeeAmt', 5, 2);
            $table->float('NAChildCrdAvail', 5, 2);
            $table->float('NACreditSharedPrc', 5, 2);
            $table->float('NAParentCreditPrc', 5, 2);
            $table->float('OversPct', 5, 2);
            $table->float('PriceTolerance', 5, 2);
            $table->float('UndersPct', 5, 2);
            $table->integer('BTCountryNum');
            $table->integer('BillDay');
            $table->integer('ChangeTime');
            $table->integer('ContBillDay');
            $table->integer('CountryNum');
            $table->integer('CreditLimit');
            $table->integer('CustNum');
            $table->integer('CustPILimit');
            $table->integer('DeliveryConf');
            $table->integer('DemandDeliveryDays');
            $table->integer('DocGlobalCreditLimit');
            $table->integer('DocGlobalPILimit');
            $table->integer('EarlyBuffer');
            $table->integer('FFCountryNum');
            $table->integer('GlobalCreditLimit');
            $table->integer('GlobalPILimit');
            $table->integer('INGSTComplianceRate');
            $table->integer('LateBuffer');
            $table->integer('LinkPortNum');
            $table->integer('ManagedVendNum');
            $table->integer('NumberOfEmployees');
            $table->integer('PBTerms');
            $table->integer('PMUID');
            $table->integer('ParentCustNum');
            $table->integer('PeriodicityCode');
            $table->integer('PrimBCon');
            $table->integer('PrimPCon');
            $table->integer('PrimSCon');
            $table->integer('RebateVendorNum');
            $table->integer('SysRevID');
            $table->integer('TWTaxPayerType');
            $table->integer('TaxRoundRule');
            $table->string('ACATRespCareType', 75);
            $table->string('ACATRespCareTypeDesc', 75);
            $table->string('AEPLOQType', 75);
            $table->string('AGAFIPResponsibilityCode', 75);
            $table->string('AGBillToProvinceCode', 75);
            $table->string('AGGrossIncomeTaxID', 75);
            $table->string('AGIDDocTypeCode', 75);
            $table->string('AGIDDocumentNumber', 75);
            $table->string('AGProvinceCode', 75);
            $table->string('ARInvoiceAdjITCode', 75);
            $table->string('AddrList', 75);
            $table->string('Address1', 75);
            $table->string('Address2', 75);
            $table->string('Address3', 75);
            $table->string('AgingCreditClearUserID', 75);
            $table->string('AgingCreditCode', 75);
            $table->string('AgingCreditHoldSource', 75);
            $table->string('AllocPriorityCode', 75);
            $table->string('AttrCodeList', 75);
            $table->string('BTAddress1', 75);
            $table->string('BTAddress2', 75);
            $table->string('BTAddress3', 75);
            $table->string('BTCity', 75);
            $table->string('BTCountry', 75);
            $table->string('BTFaxNum', 75);
            $table->string('BTFormatStr', 75);
            $table->string('BTName', 75);
            $table->string('BTPhoneNum', 75);
            $table->string('BTState', 75);
            $table->string('BTZip', 75);
            $table->string('BillFrequency', 75);
            $table->string('BorderCrossing', 75);
            $table->string('BusinessCust', 75);
            $table->string('CSR', 75);
            $table->string('ChangedBy', 75);
            $table->string('City', 75);
            $table->string('Comment', 75);
            $table->string('Country', 30);
            $table->string('CredNextAction_c', 75);
            $table->string('CreditApplication_c', 75);
            $table->string('CreditClearTime', 75);
            $table->string('CreditClearUserID', 75);
            $table->string('CreditCollectionStatus_c', 75);
            $table->string('CreditHoldSource', 75);
            $table->string('CurrencyCode', 75);
            $table->string('CustCreditNotes_c', 75);
            $table->string('CustID', 75);
            $table->string('CustPartOpts', 75);
            $table->string('CustPricingSchema', 75);
            $table->string('CustURL', 75);
            $table->string('CustomerType', 75);
            $table->string('DefaultFOB', 75);
            $table->string('DefaultInvoicestyle', 75);
            $table->string('DeliveryType', 75);
            $table->string('DemandCheckCUMMAction', 75);
            $table->string('DemandCheckCfgAction', 75);
            $table->string('DemandCheckForPartAction', 75);
            $table->string('DemandCheckForRevAction', 75);
            $table->string('DemandPricing', 75);
            $table->string('DemandUnitPriceDiffAction', 75);
            $table->string('DiscountQualifier', 75);
            $table->string('DmdCheckShipAction', 75);
            $table->string('DueDateCriteria', 75);
            $table->string('EAddress', 75);
            $table->string('ECCType', 75);
            $table->string('EDICode', 75);
            $table->string('EInvEndpointIDAttr', 75);
            $table->string('EMailAddress', 75);
            $table->string('EmailInvAddress_c', 75);
            $table->string('EntityUseCode', 75);
            $table->string('ExtID', 75);
            $table->string('ExternalID', 75);
            $table->string('FFAddress1', 75);
            $table->string('FFAddress2', 75);
            $table->string('FFAddress3', 75);
            $table->string('FFCity', 75);
            $table->string('FFCompName', 75);
            $table->string('FFContact', 75);
            $table->string('FFCountry', 75);
            $table->string('FFID', 75);
            $table->string('FFPhoneNum', 75);
            $table->string('FFState', 75);
            $table->string('FFZip', 75);
            $table->string('FaxNum', 75);
            $table->string('FederalID', 75);
            $table->string('FormatStr', 75);
            $table->string('GlobalCreditHold', 75);
            $table->string('GlobalCurrencyCode', 75);
            $table->string('GroundType', 75);
            $table->string('GroupCode', 75);
            $table->string('INTaxRegistrationID', 75);
            $table->string('Industry', 75);
            $table->string('IntCustomerComments_c', 75);
            $table->string('LangNameID', 75);
            $table->string('LegalName', 75);
            $table->string('ListCode', 75);
            $table->string('MXAccountNumber', 75);
            $table->string('MXCURP', 75);
            $table->string('MXMunicipio', 75);
            $table->string('MXPurchaseType', 75);
            $table->string('MYIndustryCode', 75);
            $table->string('ManagedVendID', 75);
            $table->string('MarkUpID', 75);
            $table->string('NACreditPreferenceList', 75);
            $table->string('NARlsClassCode', 75);
            $table->string('Name', 75);
            $table->string('NotifyEMail', 75);
            $table->string('OREmployee_c', 75);
            $table->string('OTSSaveAs', 75);
            $table->string('OrgRegCode', 75);
            $table->string('OurBankCode', 75);
            $table->string('OurSupplierCode', 75);
            $table->string('Ownership', 75);
            $table->string('PEAddressID', 75);
            $table->string('PEDocumentID', 75);
            $table->string('PEIdentityDocType', 75);
            $table->string('PEPerceptionRegime', 75);
            $table->string('ParamCode', 75);
            $table->string('ParentCustID_c', 75);
            $table->string('PendingTerritoryID', 75);
            $table->string('PhoneNum', 75);
            $table->string('PreferredBank', 75);
            $table->string('RACode', 75);
            $table->string('Rating', 75);
            $table->string('RebateForm', 75);
            $table->string('RefNotes', 500);
            $table->string('RegistrationCode', 75);
            $table->string('ReminderCode', 75);
            $table->string('ResaleID', 75);
            $table->string('ReservePriorityCode', 75);
            $table->string('SEC', 75);
            $table->string('SalesRepCode', 75);
            $table->string('ServAuthNum', 75);
            $table->string('ServInstruct', 75);
            $table->string('ServPhone', 75);
            $table->string('ShipToNum', 75);
            $table->string('ShipToTerrList', 75);
            $table->string('ShipViaCode', 75);
            $table->string('ShippingQualifier', 75);
            $table->string('State', 75);
            $table->string('SysRowID', 75);
            $table->string('THBranchID', 75);
            $table->string('TWDeductGUIFormatCode', 75);
            $table->string('TWGUIRegNum', 75);
            $table->string('TaxAuthorityCode', 75);
            $table->string('TaxEntityType', 75);
            $table->string('TaxExempt', 75);
            $table->string('TaxMethod', 75);
            $table->string('TaxRegReason', 75);
            $table->string('TaxRegionCode', 75);
            $table->string('TermsCode', 75);
            $table->string('TerritoryID', 75);
            $table->string('TickerLocation', 75);
            $table->string('TickerSymbol', 75);
            $table->string('UPSQVEmailType', 75);
            $table->string('UPSQVMemo', 75);
            $table->string('UPSQVShipFromName', 75);
            $table->string('WIApplication', 75);
            $table->string('WICustomer', 75);
            $table->string('Zip', 75);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('customers');
    }
}
