<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOrderItemsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('order_items', function (Blueprint $table) {
            $table->id();

            // Table to be sorted for nullable fields and defaults

            $table->boolean('Commissionable');
            $table->boolean('CounterSale');
            $table->boolean('CreateJob');
            $table->boolean('CreateNewJob');
            $table->boolean('CurrencySwitch');
            $table->boolean('CustNumSendToFSA');
            $table->boolean('DemandDtlRejected');
            $table->boolean('DupOnJobCrt');
            $table->boolean('ECCPreventRepricing');
            $table->boolean('EnableCreateNewJob');
            $table->boolean('EnableDynAttrButton');
            $table->boolean('EnableGetDtls');
            $table->boolean('EnableKitUnitPrice');
            $table->boolean('EnableRelJob');
            $table->boolean('EnableRenewalNbr');
            $table->boolean('EnableSchedJob');
            $table->boolean('EnableSellingQty');
            $table->boolean('FSAInstallationRequired');
            $table->boolean('FromQuoteLineFlag');
            $table->boolean('GetDtls');
            $table->boolean('HasComplement');
            $table->boolean('HasDowngrade');
            $table->boolean('HasSubstitute');
            $table->boolean('HasUpgrade');
            $table->boolean('InPrice');
            $table->boolean('JobWasCreated');
            $table->boolean('KitAllowUpdate');
            $table->boolean('KitBackFlush');
            $table->boolean('KitChangeParms');
            $table->boolean('KitDisable');
            $table->boolean('KitPrintCompsInv');
            $table->boolean('KitPrintCompsPS');
            $table->boolean('KitShipComplete');
            $table->boolean('KitStandard');
            $table->boolean('KitsLoaded');
            $table->boolean('LabCovered');
            $table->boolean('LinkToContract');
            $table->boolean('Linked');
            $table->boolean('LockDisc');
            $table->boolean('LockPrice');
            $table->boolean('LockQty');
            $table->boolean('MatCovered');
            $table->boolean('MiscCovered');
            $table->boolean('MultipleReleases');
            $table->boolean('NonStd_c');
            $table->boolean('Onsite');
            $table->boolean('OpenLine');
            $table->boolean('OverrideDiscPriceList');
            $table->boolean('OverridePriceList');
            $table->boolean('PCLinkRemoved');
            $table->boolean('PartExists');
            $table->boolean('PartNumFSAEquipment');
            $table->boolean('PartNumSendToFSA');
            $table->boolean('PartNumTrackDimension');
            $table->boolean('PartNumTrackLots');
            $table->boolean('PartNumTrackSerialNum');
            $table->boolean('PartTrackDimension');
            $table->boolean('PartTrackLots');
            $table->boolean('ProcessCounterSale');
            $table->boolean('ProcessQuickEntry');
            $table->boolean('RelJob');
            $table->boolean('RelWasRecInvoiced');
            $table->boolean('ReverseCharge');
            $table->boolean('Rework');
            $table->boolean('RunOut_c');
            $table->boolean('SchedJob');
            $table->boolean('ShipLineComplete');
            $table->boolean('SmartStringProcessed');
            $table->boolean('TMBilling');
            $table->boolean('VoidLine');
            $table->boolean('Warranty');
            $table->float('AdvanceBillBal', 5, 2);
            $table->float('CalcUnitPrice', 5, 2);
            $table->float('ConfigBaseUnitPrice', 5, 2);
            $table->float('ConfigUnitPrice', 5, 2);
            $table->float('CumeQty', 5, 2);
            $table->float('DemandQuantity', 5, 2);
            $table->float('DimConvFactor', 5, 2);
            $table->float('DiscListPrice', 5, 2);
            $table->float('Discount', 5, 2);
            $table->float('DiscountPercent', 5, 2);
            $table->float('DisplaySeq', 5, 2);
            $table->float('DocAdvanceBillBal', 5, 2);
            $table->float('DocDiscount', 5, 2);
            $table->float('DocDspDiscount', 5, 2);
            $table->float('DocDspUnitPrice', 5, 2);
            $table->float('DocExtPrice', 5, 2);
            $table->float('DocExtPriceDtl', 5, 2);
            $table->float('DocInAdvanceBillBal', 5, 2);
            $table->float('DocInDiscount', 5, 2);
            $table->float('DocInExtPriceDtl', 5, 2);
            $table->float('DocInListPrice', 5, 2);
            $table->float('DocInOrdBasedPrice', 5, 2);
            $table->float('DocInUnitPrice', 5, 2);
            $table->float('DocLessDiscount', 5, 2);
            $table->float('DocListPrice', 5, 2);
            $table->float('DocOrdBasedPrice', 5, 2);
            $table->float('DocTotalPrice', 5, 2);
            $table->float('DocUnitPrice', 5, 2);
            $table->float('DspDiscount', 5, 2);
            $table->float('DspUnitPrice', 5, 2);
            $table->float('ECCDiscount', 5, 2);
            $table->float('ExtPrice', 5, 2);
            $table->float('ExtPriceDtl', 5, 2);
            $table->float('FSAInstallationCost', 5, 2);
            $table->float('InAdvanceBillBal', 5, 2);
            $table->float('InDiscount', 5, 2);
            $table->float('InExtPriceDtl', 5, 2);
            $table->float('InListPrice', 5, 2);
            $table->float('InOrdBasedPrice', 5, 2);
            $table->float('InUnitPrice', 5, 2);
            $table->float('KitQtyPer', 5, 2);
            $table->float('LessDiscount', 5, 2);
            $table->float('ListPrice', 5, 2);
            $table->float('OldOpenValue', 5, 2);
            $table->float('OldOurOpenQty', 5, 2);
            $table->float('OldSellingOpenQty', 5, 2);
            $table->float('OrdBasedPrice', 5, 2);
            $table->float('OrderQty', 5, 2);
            $table->float('Overs', 5, 2);
            $table->float('OversUnitPrice', 5, 2);
            $table->float('PartNumSellingFactor', 5, 2);
            $table->float('PrevSellQty', 5, 2);
            $table->float('PricingQty', 5, 2);
            $table->float('PricingValue', 5, 2);
            $table->float('RepRate1', 5, 2);
            $table->float('RepRate2', 5, 2);
            $table->float('RepRate3', 5, 2);
            $table->float('RepRate4', 5, 2);
            $table->float('RepRate5', 5, 2);
            $table->float('Rpt1AdvanceBillBal', 5, 2);
            $table->float('Rpt1Discount', 5, 2);
            $table->float('Rpt1DspDiscount', 5, 2);
            $table->float('Rpt1DspUnitPrice', 5, 2);
            $table->float('Rpt1ExtPrice', 5, 2);
            $table->float('Rpt1ExtPriceDtl', 5, 2);
            $table->float('Rpt1InAdvanceBillBal', 5, 2);
            $table->float('Rpt1InDiscount', 5, 2);
            $table->float('Rpt1InExtPriceDtl', 5, 2);
            $table->float('Rpt1InListPrice', 5, 2);
            $table->float('Rpt1InOrdBasedPrice', 5, 2);
            $table->float('Rpt1InUnitPrice', 5, 2);
            $table->float('Rpt1LessDiscount', 5, 2);
            $table->float('Rpt1ListPrice', 5, 2);
            $table->float('Rpt1OrdBasedPrice', 5, 2);
            $table->float('Rpt1TotalPrice', 5, 2);
            $table->float('Rpt1UnitPrice', 5, 2);
            $table->float('Rpt2AdvanceBillBal', 5, 2);
            $table->float('Rpt2Discount', 5, 2);
            $table->float('Rpt2DspDiscount', 5, 2);
            $table->float('Rpt2DspUnitPrice', 5, 2);
            $table->float('Rpt2ExtPrice', 5, 2);
            $table->float('Rpt2ExtPriceDtl', 5, 2);
            $table->float('Rpt2InAdvanceBillBal', 5, 2);
            $table->float('Rpt2InDiscount', 5, 2);
            $table->float('Rpt2InExtPriceDtl', 5, 2);
            $table->float('Rpt2InListPrice', 5, 2);
            $table->float('Rpt2InOrdBasedPrice', 5, 2);
            $table->float('Rpt2InUnitPrice', 5, 2);
            $table->float('Rpt2LessDiscount', 5, 2);
            $table->float('Rpt2ListPrice', 5, 2);
            $table->float('Rpt2OrdBasedPrice', 5, 2);
            $table->float('Rpt2TotalPrice', 5, 2);
            $table->float('Rpt2UnitPrice', 5, 2);
            $table->float('Rpt3AdvanceBillBal', 5, 2);
            $table->float('Rpt3Discount', 5, 2);
            $table->float('Rpt3DspDiscount', 5, 2);
            $table->float('Rpt3DspUnitPrice', 5, 2);
            $table->float('Rpt3ExtPrice', 5, 2);
            $table->float('Rpt3ExtPriceDtl', 5, 2);
            $table->float('Rpt3InAdvanceBillBal', 5, 2);
            $table->float('Rpt3InDiscount', 5, 2);
            $table->float('Rpt3InExtPriceDtl', 5, 2);
            $table->float('Rpt3InListPrice', 5, 2);
            $table->float('Rpt3InOrdBasedPrice', 5, 2);
            $table->float('Rpt3InUnitPrice', 5, 2);
            $table->float('Rpt3LessDiscount', 5, 2);
            $table->float('Rpt3ListPrice', 5, 2);
            $table->float('Rpt3OrdBasedPrice', 5, 2);
            $table->float('Rpt3TotalPrice', 5, 2);
            $table->float('Rpt3UnitPrice', 5, 2);
            $table->float('SellingFactor', 5, 2);
            $table->float('SellingQuantity', 5, 2);
            $table->float('ThisOrderInvtyQty', 5, 2);
            $table->float('TotalPrice', 5, 2);
            $table->float('Unders', 5, 2);
            $table->float('UndersPct', 5, 2);
            $table->float('UnitPrice', 5, 2);
            $table->integer('AvailableQuantity');
            $table->integer('BitFlag');
            $table->integer('ChangeTime');
            $table->integer('ContractNum');
            $table->integer('CustNum');
            $table->integer('DemandContractLine');
            $table->integer('DemandContractNum');
            $table->integer('DemandDtlSeq');
            $table->integer('DemandHeadSeq');
            $table->integer('DocEndCustomerPrice');
            $table->integer('DocInMiscCharges');
            $table->integer('DocMSRP');
            $table->integer('DocMiscCharges');
            $table->integer('DocPromotionalPrice');
            $table->integer('DocTaxAmt');
            $table->integer('ECCOrderLine');
            $table->integer('ECCQuoteLine');
            $table->integer('EndCustomerPrice');
            $table->integer('FSAInstallationOrderLine');
            $table->integer('FSAInstallationOrderNum');
            $table->integer('GroupSeq');
            $table->integer('ICPOLine');
            $table->integer('ICPONum');
            $table->integer('InMiscCharges');
            $table->integer('KitCompOrigSeq');
            $table->integer('KitParentLine');
            $table->integer('LaborDuration');
            $table->integer('LastConfigTime');
            $table->integer('MSRP');
            $table->integer('MaterialDuration');
            $table->integer('MiscCharges');
            $table->integer('MiscDuration');
            $table->integer('MktgEvntSeq');
            $table->integer('NextPriceBreak_c');
            $table->integer('OnHandQuantity');
            $table->integer('OrderLine');
            $table->integer('OrderNum');
            $table->integer('OrderNumBTCustNum');
            $table->integer('PromotionalPrice');
            $table->integer('QuoteLine');
            $table->integer('QuoteNum');
            $table->integer('QuoteQtyNum');
            $table->integer('RMALine');
            $table->integer('RMANum');
            $table->integer('RenewalNbr');
            $table->integer('RepSplit1');
            $table->integer('RepSplit2');
            $table->integer('RepSplit3');
            $table->integer('RepSplit4');
            $table->integer('RepSplit5');
            $table->integer('Rpt1EndCustomerPrice');
            $table->integer('Rpt1InMiscCharges');
            $table->integer('Rpt1MSRP');
            $table->integer('Rpt1MiscCharges');
            $table->integer('Rpt1PromotionalPrice');
            $table->integer('Rpt1TaxAmt');
            $table->integer('Rpt2EndCustomerPrice');
            $table->integer('Rpt2InMiscCharges');
            $table->integer('Rpt2MSRP');
            $table->integer('Rpt2MiscCharges');
            $table->integer('Rpt2PromotionalPrice');
            $table->integer('Rpt2TaxAmt');
            $table->integer('Rpt3EndCustomerPrice');
            $table->integer('Rpt3InMiscCharges');
            $table->integer('Rpt3MSRP');
            $table->integer('Rpt3MiscCharges');
            $table->integer('Rpt3PromotionalPrice');
            $table->integer('Rpt3TaxAmt');
            $table->integer('SysRevID');
            $table->integer('TaxAmt');
            $table->integer('TotalReleases');
            $table->integer('TotalShipped');
            $table->string('AvailPriceLists', 75);
            $table->string('AvailUMFromQuote', 75);
            $table->string('BaseCurrSymbol', 75);
            $table->string('BaseCurrencyID', 75);
            $table->string('BasePartNum', 75);
            $table->string('BaseRevisionNum', 75);
            $table->string('BinNum', 75);
            $table->string('BreakListCode', 75);
            $table->string('ChangeDate', 75);
            $table->string('ChangedBy', 75);
            $table->string('CommodityCode', 75);
            $table->string('CommodityCodeDescription', 75);
            $table->string('Company', 75);
            $table->string('ConfigType', 75);
            $table->string('Configured', 75);
            $table->string('ContractCode', 75);
            $table->string('ContractCodeContractDescription', 75);
            $table->string('ContractID', 75);
            $table->string('CounterSaleBinNum', 75);
            $table->string('CounterSaleDimCode', 75);
            $table->string('CounterSaleLotNum', 75);
            $table->string('CounterSaleWarehouse', 75);
            $table->string('CreditLimitMessage', 75);
            $table->string('CreditLimitSource', 75);
            $table->string('CurrSymbol', 75);
            $table->string('CurrencyCode', 75);
            $table->string('CurrencyID', 75);
            $table->string('CustNumBTName', 75);
            $table->string('CustNumCustID', 75);
            $table->string('CustNumName', 75);
            $table->string('DUM', 75);
            $table->string('DefaultOversPricing', 75);
            $table->string('DimCode', 75);
            $table->string('DiscBreakListCode', 75);
            $table->string('DiscBreakListCodeListDescription', 75);
            $table->string('DspJobType', 75);
            $table->string('ECCConfigSysRowId', 75);
            $table->string('ECCOrderNum', 75);
            $table->string('ECCPlant', 75);
            $table->string('ECCQuoteNum', 75);
            $table->string('EntryProcess', 75);
            $table->string('ExtCompany', 75);
            $table->string('FSAInstallationType', 75);
            $table->string('FSAInstallationTypeDescription', 75);
            $table->string('IUM', 75);
            $table->string('IntExternalKey', 75);
            $table->string('InternalComment_c', 75);
            $table->string('InvoiceComment', 75);
            $table->string('InvtyUOM', 75);
            $table->string('JobTypeDesc', 75);
            $table->string('KitCompOrigPart', 75);
            $table->string('KitFlag', 75);
            $table->string('KitFlagDescription', 75);
            $table->string('KitOrderQtyUOM', 75);
            $table->string('KitPricing', 75);
            $table->string('LaborMod', 75);
            $table->string('LastConfigUserID', 75);
            $table->string('LineDesc', 75);
            $table->string('LineStatus', 75);
            $table->string('LineType', 75);
            $table->string('NeedByDate', 75);
            $table->string('OrderComment', 75);
            $table->string('OrderLineStatusCode', 75);
            $table->string('OrderNumCardMemberName', 75);
            $table->string('OrderNumCurrencyCode', 75);
            $table->string('OrigWhyNoTax', 75);
            $table->string('POLine', 75);
            $table->string('POLineRef', 75);
            $table->string('PartNum', 75);
            $table->string('PartNumIUM', 75);
            $table->string('PartNumPartDescription', 75);
            $table->string('PartNumPricePerCode', 75);
            $table->string('PartNumSalesUM', 75);
            $table->string('PickListComment', 75);
            $table->string('PlanGUID', 75);
            $table->string('PlanUserID', 75);
            $table->string('PrevPartNum', 75);
            $table->string('PrevXPartNum', 75);
            $table->string('PriceBreakListDescription', 75);
            $table->string('PriceGroupCode', 75);
            $table->string('PriceListCode', 75);
            $table->string('PriceListCodeDesc', 75);
            $table->string('PricePerCode', 75);
            $table->string('ProFormaInvComment', 75);
            $table->string('ProdCode', 75);
            $table->string('ProdCodeDescription', 75);
            $table->string('ProjectID', 75);
            $table->string('ProjectIDDescription', 75);
            $table->string('QuoteNumCurrencyCode', 75);
            $table->string('Reference', 75);
            $table->string('RequestDate', 75);
            $table->string('RespMessage', 75);
            $table->string('ShipComment', 75);
            $table->string('SmartString', 75);
            $table->string('SysRowID', 75);
            $table->string('TaxCatID', 75);
            $table->string('TaxCatIDDescription', 75);
            $table->string('UD_SysRevID', 75);
            $table->string('WarehouseCode', 75);
            $table->string('WarehouseDesc', 75);
            $table->string('WarrantyCode', 75);
            $table->string('WarrantyCodeWarrDescription', 75);
            $table->string('WarrantyComment', 75);
            $table->string('XPartNum', 75);
            $table->string('XRevisionNum', 75);

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('order_items');
    }
}
