<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->id();

            // Table to be sorted for nullable fields and defaults

      $table->boolean('AGUseGoodDefaultMark');
            $table->boolean('AWCC_CreditCardOrder_c');
            $table->boolean('AckEmailSent');
            $table->boolean('AddlHdlgFlag');
            $table->boolean('ApplyChrg');
            $table->boolean('ApplyOrderBasedDisc');
            $table->boolean('AutoEmailAck_c');
            $table->boolean('AutoOrderBasedDisc');
            $table->boolean('AutoPrintReady');
            $table->boolean('CCIsTraining');
            $table->boolean('COD');
            $table->boolean('CODCheck');
            $table->boolean('CODFreight');
            $table->boolean('CanChangeTaxLiab');
            $table->boolean('CertOfOrigin');
            $table->boolean('CommercialInvoice');
            $table->boolean('CounterSale');
            $table->boolean('CreateInvoice');
            $table->boolean('CreatePackingSlip');
            $table->boolean('CreditCardOrder');
            $table->boolean('CreditHold_c');
            $table->boolean('CreditOverride');
            $table->boolean('CurrencySwitch');
            $table->boolean('CustAllowOTS');
            $table->boolean('CustOnCreditHold');
            $table->boolean('CustomerAllowShipTo3');
            $table->boolean('CustomerPrintAck');
            $table->boolean('CustomerRequiresPO');
            $table->boolean('DeclaredIns');
            $table->boolean('DemandRejected');
            $table->boolean('DocOnly');
            $table->boolean('DropShip');
            $table->boolean('EDIAck');
            $table->boolean('EDIOrder');
            $table->boolean('EDIReady');
            $table->boolean('ERSOrder');
            $table->boolean('ERSOverride');
            $table->boolean('EnableCreditCard');
            $table->boolean('EnableJobWizard');
            $table->boolean('EnableSoldToID');
            $table->boolean('HamiltonOrder_c');
            $table->boolean('HasMiscCharges');
            $table->boolean('HasOrderLines');
            $table->boolean('Hazmat');
            $table->boolean('HoldSetByDemand');
            $table->boolean('InPrice');
            $table->boolean('IndividualPackIDs');
            $table->boolean('IntrntlShip');
            $table->boolean('InvcOrderCmp');
            $table->boolean('IsCSRSet');
            $table->boolean('LOCHold');
            $table->boolean('LetterOfInstr');
            $table->boolean('Linked');
            $table->boolean('LockQty');
            $table->boolean('LockRate');
            $table->boolean('NoTaxRgnChange');
            $table->boolean('NonStandard_c');
            $table->boolean('NonStdPkg');
            $table->boolean('NotifyFlag');
            $table->boolean('OTSCustSaved');
            $table->boolean('OTSSaved');
            $table->boolean('OpenOrder');
            $table->boolean('OrderHeld');
            $table->boolean('OverrideCarrier');
            $table->boolean('OverrideService');
            $table->boolean('ReadyToCalc');
            $table->boolean('ReadyToFulfill');
            $table->boolean('ReprintSOAck');
            $table->boolean('ResDelivery');
            $table->boolean('ResetBTCustAddr');
            $table->boolean('ResetRelTaxRgn');
            $table->boolean('SatDelivery');
            $table->boolean('SatPickup');
            $table->boolean('ServAlert');
            $table->boolean('ServHomeDel');
            $table->boolean('ServRelease');
            $table->boolean('ServSignature');
            $table->boolean('ShipExprtDeclartn');
            $table->boolean('ShipOrderComplete');
            $table->boolean('ShowApplyOrderDiscountsControl');
            $table->boolean('SndAlrtShp');
            $table->boolean('UPSQuantumView');
            $table->boolean('UpdateDtlAndRelRecords');
            $table->boolean('UseOTS');
            $table->boolean('VoidOrder');
            $table->boolean('WICreditCardorder');
            $table->boolean('WebOrder');
            $table->float('CCAmount', 5, 2);
            $table->float('CCDocAmount', 5, 2);
            $table->float('CCDocFreight', 5, 2);
            $table->float('CCDocTax', 5, 2);
            $table->float('CCDocTotal', 5, 2);
            $table->float('CCFreight', 5, 2);
            $table->float('CCRounding', 5, 2);
            $table->float('CCTax', 5, 2);
            $table->float('CCTotal', 5, 2);
            $table->float('CODAmount', 5, 2);
            $table->float('ChrgAmount', 5, 2);
            $table->float('ClosedNotShipped', 5, 2);
            $table->float('CreditOverrideLimit', 5, 2);
            $table->float('DeclaredAmt', 5, 2);
            $table->float('DepositBal', 5, 2);
            $table->float('DiscountPercent', 5, 2);
            $table->float('DocCCRounding', 5, 2);
            $table->float('DocDepositBal', 5, 2);
            $table->float('DocInTotalCharges', 5, 2);
            $table->float('DocInTotalDiscount', 5, 2);
            $table->float('DocInTotalMisc', 5, 2);
            $table->float('DocOrderAmt', 5, 2);
            $table->float('DocRounding', 5, 2);
            $table->float('DocTotalAdvBill', 5, 2);
            $table->float('DocTotalCharges', 5, 2);
            $table->float('DocTotalComm', 5, 2);
            $table->float('DocTotalDiscount', 5, 2);
            $table->float('DocTotalMisc', 5, 2);
            $table->float('DocTotalNet', 5, 2);
            $table->float('DocTotalOrder', 5, 2);
            $table->float('DocTotalSATax', 5, 2);
            $table->float('DocTotalTax', 5, 2);
            $table->float('DocTotalWHTax', 5, 2);
            $table->float('InTotalCharges', 5, 2);
            $table->float('InTotalDiscount', 5, 2);
            $table->float('InTotalMisc', 5, 2);
            $table->float('InvCurrDepositBal', 5, 2);
            $table->float('OrderAmt', 5, 2);
            $table->float('OrderOpenCredit', 5, 2);
            $table->float('RepRate1', 5, 2);
            $table->float('RepRate2', 5, 2);
            $table->float('RepRate3', 5, 2);
            $table->float('RepRate4', 5, 2);
            $table->float('RepRate5', 5, 2);
            $table->float('Rounding', 5, 2);
            $table->float('Rpt1CCAmount', 5, 2);
            $table->float('Rpt1CCFreight', 5, 2);
            $table->float('Rpt1CCRounding', 5, 2);
            $table->float('Rpt1CCTax', 5, 2);
            $table->float('Rpt1CCTotal', 5, 2);
            $table->float('Rpt1DepositBal', 5, 2);
            $table->float('Rpt1InTotalCharges', 5, 2);
            $table->float('Rpt1InTotalDiscount', 5, 2);
            $table->float('Rpt1InTotalMisc', 5, 2);
            $table->float('Rpt1OrderAmt', 5, 2);
            $table->float('Rpt1Rounding', 5, 2);
            $table->float('Rpt1TotalAdvBill', 5, 2);
            $table->float('Rpt1TotalCharges', 5, 2);
            $table->float('Rpt1TotalComm', 5, 2);
            $table->float('Rpt1TotalDiscount', 5, 2);
            $table->float('Rpt1TotalMisc', 5, 2);
            $table->float('Rpt1TotalNet', 5, 2);
            $table->float('Rpt1TotalSATax', 5, 2);
            $table->float('Rpt1TotalTax', 5, 2);
            $table->float('Rpt1TotalWHTax', 5, 2);
            $table->float('Rpt2CCAmount', 5, 2);
            $table->float('Rpt2CCFreight', 5, 2);
            $table->float('Rpt2CCRounding', 5, 2);
            $table->float('Rpt2CCTax', 5, 2);
            $table->float('Rpt2CCTotal', 5, 2);
            $table->float('Rpt2DepositBal', 5, 2);
            $table->float('Rpt2InTotalCharges', 5, 2);
            $table->float('Rpt2InTotalDiscount', 5, 2);
            $table->float('Rpt2InTotalMisc', 5, 2);
            $table->float('Rpt2OrderAmt', 5, 2);
            $table->float('Rpt2Rounding', 5, 2);
            $table->float('Rpt2TotalAdvBill', 5, 2);
            $table->float('Rpt2TotalCharges', 5, 2);
            $table->float('Rpt2TotalComm', 5, 2);
            $table->float('Rpt2TotalDiscount', 5, 2);
            $table->float('Rpt2TotalMisc', 5, 2);
            $table->float('Rpt2TotalNet', 5, 2);
            $table->float('Rpt2TotalSATax', 5, 2);
            $table->float('Rpt2TotalTax', 5, 2);
            $table->float('Rpt2TotalWHTax', 5, 2);
            $table->float('Rpt3CCAmount', 5, 2);
            $table->float('Rpt3CCFreight', 5, 2);
            $table->float('Rpt3CCRounding', 5, 2);
            $table->float('Rpt3CCTax', 5, 2);
            $table->float('Rpt3CCTotal', 5, 2);
            $table->float('Rpt3DepositBal', 5, 2);
            $table->float('Rpt3InTotalCharges', 5, 2);
            $table->float('Rpt3InTotalDiscount', 5, 2);
            $table->float('Rpt3InTotalMisc', 5, 2);
            $table->float('Rpt3OrderAmt', 5, 2);
            $table->float('Rpt3Rounding', 5, 2);
            $table->float('Rpt3TotalAdvBill', 5, 2);
            $table->float('Rpt3TotalCharges', 5, 2);
            $table->float('Rpt3TotalComm', 5, 2);
            $table->float('Rpt3TotalDiscount', 5, 2);
            $table->float('Rpt3TotalMisc', 5, 2);
            $table->float('Rpt3TotalNet', 5, 2);
            $table->float('Rpt3TotalSATax', 5, 2);
            $table->float('Rpt3TotalTax', 5, 2);
            $table->float('Rpt3TotalWHTax', 5, 2);
            $table->float('SRCommAmt1', 5, 2);
            $table->float('SRCommAmt2', 5, 2);
            $table->float('SRCommAmt3', 5, 2);
            $table->float('SRCommAmt4', 5, 2);
            $table->float('SRCommAmt5', 5, 2);
            $table->float('SRCommableAmt1', 5, 2);
            $table->float('SRCommableAmt2', 5, 2);
            $table->float('SRCommableAmt3', 5, 2);
            $table->float('SRCommableAmt4', 5, 2);
            $table->float('SRCommableAmt5', 5, 2);
            $table->float('TotalAdvBill', 5, 2);
            $table->float('TotalCharges', 5, 2);
            $table->float('TotalComm', 5, 2);
            $table->float('TotalDiscount', 5, 2);
            $table->float('TotalInvoiced', 5, 2);
            $table->float('TotalMisc', 5, 2);
            $table->float('TotalNet', 5, 2);
            $table->float('TotalOrder', 5, 2);
            $table->float('TotalSATax', 5, 2);
            $table->float('TotalShipped', 5, 2);
            $table->float('TotalTax', 5, 2);
            $table->float('TotalWHTax', 5, 2);
            $table->float('UserDecimal1', 5, 2);
            $table->float('UserDecimal2', 5, 2);
            $table->integer('BTConNum');
            $table->integer('BTCustNum');
            $table->integer('BitFlag');
            $table->integer('ChangeTime');
            $table->integer('CounterSOAck');
            $table->integer('CustNum');
            $table->integer('DeliveryConf');
            $table->integer('DemandContractNum');
            $table->integer('DemandHeadSeq');
            $table->integer('ExchangeRate');
            $table->integer('ExpirationMonth');
            $table->integer('ExpirationYear');
            $table->integer('FFCountryNum');
            $table->integer('HDCaseNum');
            $table->integer('ICPONum');
            $table->integer('OTSCountryNum');
            $table->integer('OrderNum');
            $table->integer('OutboundSalesDocCtr');
            $table->integer('OutboundShipDocsCtr');
            $table->integer('ParentCustNum');
            $table->integer('PayBTCountryNum');
            $table->integer('PrcConNum');
            $table->integer('RepSplit1');
            $table->integer('RepSplit2');
            $table->integer('RepSplit3');
            $table->integer('RepSplit4');
            $table->integer('RepSplit5');
            $table->integer('ShipByTime');
            $table->integer('ShipToCustNum');
            $table->integer('ShpConNum');
            $table->integer('SysRevID');
            $table->integer('TWFiscalPeriod');
            $table->integer('TWFiscalYear');
            $table->integer('TotalCommLines');
            $table->integer('TotalLines');
            $table->integer('TotalRelDates');
            $table->integer('TotalReleases');
            $table->integer('TrueDiscountPercent');
            $table->integer('UserInteger1');
            $table->integer('UserInteger2');
            $table->string('ARLOCID',75);
            $table->string('AVSAddr',75);
            $table->string('AVSZip',75);
            $table->string('AllocPriorityCode',75);
            $table->string('AvailBTCustList',75);
            $table->string('BTAddressList',75);
            $table->string('BTContactEMailAddress',75);
            $table->string('BTContactFaxNum',75);
            $table->string('BTContactName',75);
            $table->string('BTContactPhoneNum',75);
            $table->string('BTCustID',75);
            $table->string('BaseCurrSymbol',75);
            $table->string('BaseCurrencyID',75);
            $table->string('BillToCustomerName',75);
            $table->string('CardmemberReference',75);
            $table->string('ChangeDate',75);
            $table->string('ChangedBy',75);
            $table->string('Company',75);
            $table->string('CurrencyCode',75);
            $table->string('DemandContract',75);
            $table->string('DispatchReason',75);
            $table->string('ECCEmail',75);
            $table->string('ECCPaymentMethod',75);
            $table->string('EntryMethod',75);
            $table->string('EntryPerson',75);
            $table->string('ExtAOE',75);
            $table->string('ExtAOEUserID',75);
            $table->string('ExtCompany',75);
            $table->string('FFAddress1',75);
            $table->string('FFAddress2',75);
            $table->string('FFAddress3',75);
            $table->string('FFCity',75);
            $table->string('FFCompName',75);
            $table->string('FFContact',75);
            $table->string('FFCountry',75);
            $table->string('FFID',75);
            $table->string('FFPhoneNum',75);
            $table->string('FFState',75);
            $table->string('FFZip',75);
            $table->string('FOB',75);
            $table->string('FOBDescription',75);
            $table->string('GroundType',75);
            $table->string('HDCaseDescription',75);
            $table->string('IntExternalKey',75);
            $table->string('InvCurrCurrDesc',75);
            $table->string('InvoiceComment',75);
            $table->string('LinkMsg',75);
            $table->string('NeedByDate',75);
            $table->string('NotifyEMail',75);
            $table->string('OTSCntryDescription',75);
            $table->string('OTSSaveAs',75);
            $table->string('OTSSaveCustID',75);
            $table->string('OTSShipToNum',75);
            $table->string('OTSTaxRegionCode',75);
            $table->string('OrderComment',75);
            $table->string('OrderDate',75);
            $table->string('OrderStatus',75);
            $table->string('OurBank',75);
            $table->string('OurBankBankName',75);
            $table->string('OurBankDescription',75);
            $table->string('PL_Comments_c',75);
            $table->string('PONum',75);
            $table->string('PSCurrCurrDesc',75);
            $table->string('PackFilter_c',75);
            $table->string('PayBTAddress3',75);
            $table->string('PayBTPhone',75);
            $table->string('PickListComment',75);
            $table->string('Source_c',75);
            $table->string('SysRowID',75);
            $table->string('TWFiscalYearSuffix',75);
            $table->string('TWGUIGroup',75);
            $table->string('TWGUIRegNumBuyer',75);
            $table->string('TWGUIRegNumSeller',75);
            $table->string('TWGenerationType',75);
            $table->string('TaxRegionCode',75);
            $table->string('TermsCode',75);
            $table->string('TermsType',75);
            $table->string('TranDocTypeDescr',75);
            $table->string('UD_SysRevID',75);
            $table->string('UPSQVMemo',75);
            $table->string('UPSQVShipFromName',75);
            $table->string('WIApplication',75);
            $table->string('WIUserID',75);
            $table->string('WIUsername',75);
            $table->string('WebEntryPerson',75);
            $table->string('ccToken',75);
            $table->string('dspBTCustID',75);

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('orders');
    }
}
